services:
  mongodb:
    image: mongo:7
    container_name: itravel-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=itravel

volumes:
  mongodb_data:
